use_frameworks!

target 'PinyinChineseMatcher_Example' do
  pod 'PinyinChineseMatcher', :path => '../'

  target 'PinyinChineseMatcher_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
